general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 150       # 2.5 minutes
    on-timeout = ~/.config/hypr/hypridle/global-brightness.sh dim
    on-resume = ~/.config/hypr/hypridle/global-brightness.sh restore
}

listener {
    timeout = 150       # 2.5minutes
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
    timeout = 600       # 10 minutes
    on-timeout = loginctl lock-session
}

listener {
    timeout = 630       # 5.5 minutes
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && ~/.config/hypr/hypridle/global-brightness.sh restore
}

listener {
    timeout = 1800      # 30 minutes
    on-timeout = systemctl suspend
}
